const reports = [
  {
    id: "RPT001",
    title: "Daily Fleet Report",
    generatedBy: "Admin",
    date: "12-Jul-2026",
    status: "Generated"
  },
  {
    id: "RPT002",
    title: "Monthly Fuel Report",
    generatedBy: "Fleet Manager",
    date: "11-Jul-2026",
    status: "Generated"
  },
  {
    id: "RPT003",
    title: "Driver Performance Report",
    generatedBy: "HR",
    date: "10-Jul-2026",
    status: "Pending"
  },
  {
    id: "RPT004",
    title: "Vehicle Maintenance Report",
    generatedBy: "Maintenance Team",
    date: "09-Jul-2026",
    status: "Generated"
  }
];

export default function Reports() {
  return (
    <div style={{ padding: "30px" }}>
      <h1>Reports</h1>

      <table
        style={{
          width: "100%",
          marginTop: "20px",
          borderCollapse: "collapse",
          background: "white",
          borderRadius: "10px",
          overflow: "hidden"
        }}
      >
        <thead
          style={{
            background: "#0F172A",
            color: "white"
          }}
        >
          <tr>
            <th style={{ padding: "12px" }}>Report ID</th>
            <th>Report Name</th>
            <th>Generated By</th>
            <th>Date</th>
            <th>Status</th>
          </tr>
        </thead>

        <tbody>
          {reports.map((report) => (
            <tr
              key={report.id}
              style={{ textAlign: "center" }}
            >
              <td style={{ padding: "12px" }}>{report.id}</td>
              <td>{report.title}</td>
              <td>{report.generatedBy}</td>
              <td>{report.date}</td>
              <td>{report.status}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}